### ISSUE TITLE
User can view a list of Genshin Impact characters.

### ISSUE THREAD

**Issue by gino-hong** [gino-hong/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of Genshin Impact characters.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user should be able to see the icons and names of all available Genshin Impact characters.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96759480/171781497-9737cb03-93bd-4c42-93a9-665d95f6ebcf.png)
![image](https://user-images.githubusercontent.com/96759480/171781558-aeee45ab-a7bb-4a4d-9916-fa79d2f87b41.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Set the background of the entire web page to #00539B.
- [x] Build the navigation bar and set the background to #FF5F1F.
- [x] Add a header for the character list.
- [x] Build the html structure for how one character should be displayed with the image and the name.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
