### ISSUE TITLE
User can view the details of a Genshin Impact character.

### ISSUE THREAD

**Issue by gino-hong** [gino-hong/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of a Genshin Impact character.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the icon or name of a character, and it will open up a new page where the user can view the details of the character they clicked on.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96759480/171782411-94bf9fbf-59cf-40f9-97a8-f6be774cc805.png)
![image](https://user-images.githubusercontent.com/96759480/171782441-ce11bf5b-68ff-4fe1-af93-163f3f890efc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add event listeners to the icons and names of the characters. 
- [x] The event listeners should hide the view of the characters list and show the details page.
- [x] The details page will use XHR to populate the details page with the needed information.
- [x] The user should be able to click the characters button to go back to the characters list.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
