### ISSUE TITLE
User can save a Genshin Impact character to their favorites list.

### ISSUE THREAD

**Issue by gino-hong** [gino-hong/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a Genshin Impact character to their favorites list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user is viewing a character's details and they have not been favorited, the user will have the option to add that character to their favorites list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96759480/171782576-e6381555-7c37-43e5-ad45-49077d60bcdd.png)
![image](https://user-images.githubusercontent.com/96759480/171782618-5bfbf914-1f54-4046-9ea6-38480671c74e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a favorites button and format it so that it looks good. 
- [x] Save the character that is favorited in local storage.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
